### ISSUE TITLE
Timeout when running 'run_cpt.py'

### ISSUE THREAD

**Issue by thak123** [huggingface/alignment-handbook#190]
I have performing cpt using this [receipe](https://github.com/huggingface/alignment-handbook/tree/main/recipes/gpt2-nl).

```
2024-08-07 13:34:11 - INFO - datasets.builder - Generating train split
Generating train split: 0 examples [00:00, ? examples/s][WARNING|tokenization_utils_base.py:4101] 2024-08-07 13:34:12,926 >> Token indices sequence length is longer than the specified maximum sequence length for this model (1541 > 1024). Running this sequence through the model will result in indexing errors
Generating train split: 2230000 examples [29:59, 1466.92 examples/s][E ProcessGroupNCCL.cpp:475] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800449 milliseconds before timing out.
Generating train split: 2231702 examples [30:00, 1577.98 examples/s][E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might
run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800449 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800449 milliseconds before timing out.
[2024-08-07 14:04:13,625] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 399651 closing signal SIGTERM                                                                                               
[2024-08-07 14:04:14,553] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 1 (pid: 399652) of binary: /home/gthakkar/miniconda3/envs/handbook/bin/python                               
Traceback (most recent call last):
  File "/home/gthakkar/miniconda3/envs/handbook/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/gthakkar/miniconda3/envs/handbook/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main                                                                                          
    args.func(args)
  File "/home/gthakkar/miniconda3/envs/handbook/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command                                                                                      
    multi_gpu_launcher(args)
  File "/home/gthakkar/miniconda3/envs/handbook/lib/python3.10/site-packages/accelerate/commands/launch.py", line 734, in multi_gpu_launcher                                                                                   
    distrib_run.run(args)
  File "/home/gthakkar/miniconda3/envs/handbook/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run                                                                                                       
    elastic_launch(
  File "/home/gthakkar/miniconda3/envs/handbook/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__                                                                                         
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gthakkar/miniconda3/envs/handbook/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent                                                                                     
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=======================================================
scripts/run_cpt.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-07_14:04:13
  host      : vjm-xr.novalocal
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 399652)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 399652
```

I tried setting the ddp_timeout value for the training args, but the code doesnt respect the timeout value.

**Comment by thak123** [comment]
I ran the code on a single GPU, waited for it to create a cached dataset object, and then restarted the process with all GPUs. This worked for me to avoid timeout issues due to data preprocessing.

I saw one issue which said SFT trainer takes more time to preprocess on multi-gpu setup than single GPU.

I manually ran it on a single GPU which was not only a great speed up for preprocessing but also avoided unwanted timeout exceptions.
